# @package _group_

# === Required PlaNet fields ===
env: "CarRacing-v2"         # will be used in logging paths
term_fn: "no_termination"

# === Episode control ===
trial_length: 1000
action_repeat: 4             # like frame_skip
action_noise_std: 0.3

# === Model training settings (PlaNet) ===
num_grad_updates: 100
sequence_length: 50
batch_size: 32
free_nats: 3
kl_scale: 1.0

# === Planning settings ===
planning_horizon: 12
cem_num_iters: 10
cem_elite_ratio: 0.1
cem_population_size: 1000
cem_alpha: 0.0
cem_clipped_normal: true
